# Runs a BasicAgent (heuristic-based) on the MoveToBeaconDiscreteEnv.
# This is one of the options from the original 'run_basic.py' script.

experiment_name: "BasicAgent on MoveToBeacon (Discrete)"

# --- Environment Configuration ---
environment:
  name: "MoveToBeaconDiscreteEnv"
  params:
    distance_discrete_range: 10
    distance: 1
    screen_size: 32
    step_mul: 8
    is_visualize: true # Often useful to watch the basic agent.

# --- Agent Configuration ---
# The BasicAgent typically doesn't have hyperparameters.
agent:
  name: "BasicAgent"
  params: {} # No specific parameters needed for BasicAgent.

# --- Runner Configuration ---
# The BasicAgent doesn't train.
runner:
  total_episodes: 20
  is_training: false # BasicAgent does not learn.

  # Logging and model saving are not applicable to BasicAgent.
  tensorboard_log_dir: "" # Disable TensorBoard logging.
  model_save_dir: "" # Disable model saving.
  save_model_each_episode_num: 0
