# Trains a Double DQN (DDQN) agent with a CNN
# on the MoveToBeaconEnv (full visual features), using modular network config.

experiment_name: "DDQN (CNN) on MoveToBeacon (Full Visual)"

# --- Environment Configuration ---
environment:
  name: "MoveToBeaconEnv"
  params:
    screen_size: 32
    step_mul: 8
    is_visualize: false

# --- Agent Configuration ---
agent:
  name: "DQNAgent"
  params:
    enable_ddqn: true
    learning_rate: 0.00025
    discount_factor: 0.99
    initial_epsilon: 1.0
    epsilon_decay_rate: 0.000009 
    epsilon_min: 0.1
    target_update_freq: 1000
    memory_capacity: 100000
    batch_size: 32
    
    online_network_config:
      name: "CNNNetwork"
      params: {} 
    
    network_config: 
      name: "CNNNetwork"
      params: {}

# --- Runner Configuration ---
runner:
  total_episodes: 5000
  is_training: true
  tensorboard_log_dir: "./logs/ddqn_mtb_cnn" 
  model_save_dir: "./models"
  save_model_each_episode_num: 200
