# configs/ddqn_fcn_train_move_to_beacon_discrete.yaml
#
# Trains a Double DQN (DDQN) agent with an FCN/MLP
# on the MoveToBeaconDiscreteEnv.

experiment_name: "DDQN (FCN/MLP) on MoveToBeacon (Discrete)"

# --- Environment Configuration ---
environment:
  name: "MoveToBeaconDiscreteEnv"
  params:
    distance_discrete_range: 10
    distance: 1
    screen_size: 32
    step_mul: 8
    is_visualize: false

# --- Agent Configuration ---
agent:
  name: "DQNAgent" # Assuming DQNAgent handles DDQN logic
  params:
    enable_ddqn:
      true # IMPORTANT: Assumes your DQNAgent checks this flag.
      # If not, agent code needs modification for DDQN.
    use_cnn:
      false # Use MLP/FCN.
      # If using network factory: network_name: "MLP"

    # Hyperparameters (can be similar to DQN, but sometimes DDQN is more stable)
    batch_size: 32
    learning_rate: 0.001
    discount_factor: 0.99
    epsilon: 1.0
    epsilon_decay: 0.00001
    epsilon_min: 0.1
    target_update_freq: 1000
    memory_capacity: 50000

# --- Runner Configuration ---
runner:
  total_episodes: 1000
  is_training: true
  tensorboard_log_dir: "./logs"
  model_save_dir: "./models"
  save_model_each_episode_num: 100
