# configs/ddqn_cnn_train_move_to_beacon_full.yaml
#
# Trains a Double DQN (DDQN) agent with a CNN
# on the MoveToBeaconEnv (full visual features).

experiment_name: "DDQN (CNN) on MoveToBeacon (Full Visual)"

# --- Environment Configuration ---
environment:
  name: "MoveToBeaconEnv"
  params:
    distance_range: 8
    screen_size: 32
    step_mul: 8
    is_visualize: false

# --- Agent Configuration ---
agent:
  name: "DQNAgent" # Assuming DQNAgent handles DDQN logic
  params:
    enable_ddqn: true # IMPORTANT: Assumes your DQNAgent checks this flag.
    use_cnn:
      true # Use CNN.
      # If using network factory: network_name: "CNN"

    # Hyperparameters
    batch_size: 32
    learning_rate: 0.00025
    discount_factor: 0.99
    epsilon: 1.0
    epsilon_decay: 0.000009
    epsilon_min: 0.1
    target_update_freq: 1000
    memory_capacity: 100000

# --- Runner Configuration ---
runner:
  total_episodes: 5000
  is_training: true
  tensorboard_log_dir: "./logs" # e.g., "./logs/ddqn_mtb_cnn"
  model_save_dir: "./models"
  save_model_each_episode_num: 200
