# Evaluates a pre-trained DQN agent with a CNN on the DefeatRoachesEnv.

experiment_name: "DQN (CNN) on DefeatRoaches - Evaluation"

# --- Environment Configuration ---
environment:
  name: "DefeatRoachesEnv"
  params:
    screen_size: 32
    step_mul: 8
    is_visualize: false

# --- Agent Configuration ---
agent:
  name: "DQNAgent"
  params:
    enable_ddqn: false # Should match the trained model
    learning_rate: 0.00025
    discount_factor: 0.99
    initial_epsilon: 0.0
    epsilon_decay_rate: 0.0
    epsilon_min: 0.01
    target_update_freq: 1000
    memory_capacity: 1000
    batch_size: 128

    # --- Network Configuration ---
    # CRITICAL: This MUST match the architecture of the saved model.
    network_config:
      name: "CNNNetwork"
      params: {} # Or specific params if your trained CNN had custom ones

# --- Runner Configuration ---
runner:
  total_episodes: 50
  is_training: false
  load_model_path: "models/YOUR_TRAINED_DQN_CNN_DR_MODEL_DIRECTORY"
  tensorboard_log_dir: "./logs_eval"
  model_save_dir: ""
  save_model_each_episode_num: 0
